const GET_VIDEOGAMES = 'GET_VIDEOGAMES';
const GET_GAMES_NAME = 'GET_GAMES_NAME';
const GET_GAME_DETAIL = 'GET_GAME_DETAIL';
const IS_LOADING = "IS_LOADING";
const CLEAR_STATE = "CLEAR_STATE";

module.exports = {
    GET_VIDEOGAMES,
    GET_GAMES_NAME,
    GET_GAME_DETAIL,
    IS_LOADING,
    CLEAR_STATE
}