const GET_GAMES_NAME = 'GET_GAMES_NAME';
const GET_VIDEOGAMES = 'GET_VIDEOGAMES';
const GET_GAME_DETAIL = 'GET_GAME_DETAIL';
const IS_LOADING = "IS_LOADING";
const CLEAR_STATE = "CLEAR_STATE";
const POST_NEW_GAME = 'POST_NEW_GAME';
const GET_ALL_GENRES = 'GET_ALL_GENRES';
const GET_ALL_PLATFORMS = 'GET_ALL_PLATFORMS';
const ERROR_EXISTS = 'ERROR_EXISTS';
const CURRENT_PAGE = 'CURRENT_PAGE'

module.exports = {
    GET_GAMES_NAME,
    GET_VIDEOGAMES,
    GET_GAME_DETAIL,
    IS_LOADING,
    CLEAR_STATE,
    POST_NEW_GAME,
    GET_ALL_GENRES,
    GET_ALL_PLATFORMS,
    ERROR_EXISTS,
    CURRENT_PAGE
}